version: "3.1"

services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
        - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
        - .env
