  default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: root
    password: root
    host: database

  development:
    <<: *default
    database: rails_netflix_app_development

  test:
    <<: *default
    database: rails_netflix_app_test

  production:
    <<: *default
    database: rails_netflix_app_production
    username: root
    password: <%= ENV['RAILS_NETFLIX_APP_DATABASE_PASSWORD'] %>
    host: database
